In [1]:
# Dependencies

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn import preprocessing

%matplotlib inline

In [2]:
full_df = pd.read_csv("full_data.csv")
full_df.head()

,Unnamed: 0,Total_Insured,County_State,Total_Uninsured,Year,State_Code,County_Code,Poverty_percent_in_County,Total_Poverty_in_County,Uninsured_percent
0,0,43075,"Autauga County, AL",4002,2016,1,1,13.5,7444,8.500967
1,1,148007,"Baldwin County, AL",17733,2016,1,3,11.7,24005,10.699288
2,2,15745,"Barbour County, AL",2252,2016,1,5,29.9,6787,12.513197
3,3,15358,"Bibb County, AL",1646,2016,1,7,20.1,4099,9.680075
4,4,41382,"Blount County, AL",5704,2016,1,9,14.1,8033,12.114004

In [3]:
full_df.columns

Index(['Unnamed: 0', 'Total_Insured', 'County_State', 'Total_Uninsured',
       'Year', 'State_Code', 'County_Code', 'Poverty_percent_in_County',
       'Total_Poverty_in_County', 'Uninsured_percent'],
      dtype='object')

In [4]:
# Clean data to separate State and County. Use this later in Tableau and predictive analysis

full_df['State'] = full_df['County_State'].apply(lambda State: State.split(',')[-1])
full_df['County'] = full_df['County_State'].apply(lambda State: State.split(',')[0])
full_df.head()

,Unnamed: 0,Total_Insured,County_State,Total_Uninsured,Year,State_Code,County_Code,Poverty_percent_in_County,Total_Poverty_in_County,Uninsured_percent,State,County
0,0,43075,"Autauga County, AL",4002,2016,1,1,13.5,7444,8.500967,AL,Autauga County
1,1,148007,"Baldwin County, AL",17733,2016,1,3,11.7,24005,10.699288,AL,Baldwin County
2,2,15745,"Barbour County, AL",2252,2016,1,5,29.9,6787,12.513197,AL,Barbour County
3,3,15358,"Bibb County, AL",1646,2016,1,7,20.1,4099,9.680075,AL,Bibb County
4,4,41382,"Blount County, AL",5704,2016,1,9,14.1,8033,12.114004,AL,Blount County

In [5]:
full_df = full_df[['Unnamed: 0', 'Total_Insured',"County", "State", 'Total_Uninsured',
       'Year', 'State_Code', 'County_Code', 'Poverty_percent_in_County',
       'Total_Poverty_in_County', 'Uninsured_percent']]

In [6]:
full_df.head()

,Unnamed: 0,Total_Insured,County,State,Total_Uninsured,Year,State_Code,County_Code,Poverty_percent_in_County,Total_Poverty_in_County,Uninsured_percent
0,0,43075,Autauga County,AL,4002,2016,1,1,13.5,7444,8.500967
1,1,148007,Baldwin County,AL,17733,2016,1,3,11.7,24005,10.699288
2,2,15745,Barbour County,AL,2252,2016,1,5,29.9,6787,12.513197
3,3,15358,Bibb County,AL,1646,2016,1,7,20.1,4099,9.680075
4,4,41382,Blount County,AL,5704,2016,1,9,14.1,8033,12.114004

## Train Test Split

In [7]:
# Change name of dataframe

insurance_df = full_df

In [13]:
# Categorical features since they don't have integers or floats in columns 

cat_feats_1 = ['County', "State"]

In [15]:
insurance_data = pd.get_dummies(cat_feats_1, drop_first = True)

In [16]:
# Create X and y variables to train and test data. 

X = insurance_df.drop('Total_Uninsured',axis=1)
y = insurance_df['Total_Uninsured']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [17]:
le = preprocessing.LabelEncoder()
balance_data = insurance_df.apply(le.fit_transform)

In [18]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)

ValueError: could not convert string to float: ' IA'